### ISSUE TITLE
send to topcoder menu item

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/tcx-azure-devops-ext#32]
The send to topcoder menu item works great (the default project in the config used here makes sense I think). 
However, when viewing the challenge on Topcoder, the challenge page throws an error.
![image](https://user-images.githubusercontent.com/1504607/94971479-1c0b9b80-04d5-11eb-960d-78e62aa5e071.png)
looking at the console it looks like there might be an issue w/ review types?

![image](https://user-images.githubusercontent.com/1504607/94971558-40677800-04d5-11eb-9e91-67bf1eacd617.png)

perhaps there's something not set properly on the record when creating? Alternatively this could just be something annoyingly wrong w/ the Community App

**Comment by jmgasper** [comment]
@cwdcwd - I'm almost positive this is a problem with the community app in dev.  I see this all the time.  

Even if it *isn't* a problem in the community app, the API shouldn't let us set anything wrong on the record when setting it up 😉

**Comment by jmgasper** [comment]
What challenge ID is that for?

**Comment by jmgasper** [comment]
It may just take awhile to work properly.  This one showed up alright:  https://www.topcoder-dev.com/challenges/e561c7e8-10a7-4044-b2ae-62710b795310
