### ISSUE TITLE
Tags added from the plugin won't display on the page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tcx-azure-devops-ext#60]
![image](https://user-images.githubusercontent.com/42398485/99029741-43a45800-2599-11eb-8029-6c91db5138bb.png)
![image](https://user-images.githubusercontent.com/42398485/99029768-6171bd00-2599-11eb-8ea5-c3688aed2c45.png)

### Steps to reproduce the problem

1. Deploy the app and create the initial setup
2. Open Board -> Work items.
3. Open or create a work item (Issue).
4. Fill the details (Description etc)
5. Switch to Topcoder X
6. Select the project, Title, Public and private description and prize + Add Few tags (QA, NodeJS)
7. Click Save
8. Click Send to Topcoder
9. Check the challenge page opens and check the data - https://www.topcoder-dev.com/challenges/b416bcff-0011-43f7-b203-db6ba2b55fd4
10. Check the data in WM

 ### Actual behavior
- Tags added from the plugin won't display on the page

### Expected behavior
- Should display on the challenge page and should display on the WM
 
 
#### Environment
**- OS:** 10
**- Device (w/version):** Laptop, Windows 10 
**- Browser** 86.0.4240.183

**Comment by jmgasper** [comment]
Tags won't sync like this - that's not expected
