### ISSUE TITLE
Discussions added to the ticket won't display on the challenge details page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tcx-azure-devops-ext#61]
![image](https://user-images.githubusercontent.com/42398485/99030017-0391a500-259a-11eb-94f7-fd282449b25b.png)

### Steps to reproduce the problem

1. Deploy the app and create the initial setup
2. Open Board -> Work items.
3. Open or create a work item (Issue).
4. Fill the details (Description etc)
5. Switch to Topcoder X
6. Select the project, Title, Public and private description and prize + Add Few tags (QA, NodeJS)
7. Add some discussions
8. Click Save
9. Click Send to Topcoder
10. Check the challenge page opens and check the data - https://www.topcoder-dev.com/challenges/b416bcff-0011-43f7-b203-db6ba2b55fd4
11. Check the data in WM

 ### Actual behavior
- Discussions added to the ticket won't display on the challenge details page

### Expected behavior
- Should display the discussions as well
 
 
#### Environment
**- OS:** 10
**- Device (w/version):** Laptop, Windows 10 
**- Browser** 86.0.4240.183

**Comment by jmgasper** [comment]
Discussions aren't expected to sync
