### ISSUE TITLE
Done Status filter option is not present

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tcx-azure-devops-ext#64]
![image](https://user-images.githubusercontent.com/42398485/99035142-fa5a0580-25a4-11eb-868b-3761368d35aa.png)

### Steps to reproduce the problem

1. Deploy the app and create the initial setup
2. Open Board -> Work items.
3. Open or create a work item (Issue).
4. Fill the details (Description with formatting) > Save
5. Now change the status to Done
6. Check the table and click Status filter 

 ### Actual behavior
- Done Status filter option is not present

### Expected behavior
- Should be there and also the status=done items are removed from the list
 
#### Environment
**- OS:** 10
**- Device (w/version):** Laptop, Windows 10 
**- Browser** 86.0.4240.183

**Comment by jmgasper** [comment]
This isn't something we change with the plugin - this is from Azure itself.
