### ISSUE TITLE
"Send to Topcoder" from actions menu is creating new links every time

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/tcx-azure-devops-ext#66]
**Steps to reproduce the problem**
1. Open Azure DevOps, create organization, and add the TCX extension from marketplace
2. Open Board -> Work items.
2. Create new epic with title, description, date and priority > Save
4. Go to "Topcoder X" tab and fill challenging details > Send to Topcoder
5. Go to "Actions" menu and click "Send to Topcoder"

**Actual behavior**
A new link is created or perhaps a new challenge altogether

**Expected behavior**
The original challenge link should be preserved with the original challenge Id

**Environment**
- OS: Windows 10
- Device (w/version): Laptop, Windows 10
- Browser: Chrome 86.0.4240.198

![1](https://user-images.githubusercontent.com/46344490/99056328-29ca3b80-25c0-11eb-8c96-1a6ee1137bfd.PNG)
![2](https://user-images.githubusercontent.com/46344490/99056336-2b93ff00-25c0-11eb-91ff-34140b0fb3b6.PNG)
![3](https://user-images.githubusercontent.com/46344490/99056339-2cc52c00-25c0-11eb-88af-e609760eab03.PNG)

**Comment by jmgasper** [comment]
Duplicates https://github.com/topcoder-platform/tcx-azure-devops-ext/issues/55
