### ISSUE TITLE
"Send to topcoder" from actions menu is always displaying price money as 0, and also not rendering description properly

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/tcx-azure-devops-ext#67]
**Steps to reproduce the problem**
1. Open Azure DevOps, create organization, and add the TCX extension from marketplace
2. Open Board -> Work items.
2. Create new epic with title, description, date and priority > Save
4. Go to "Topcoder X" tab and fill challenging details > Send to Topcoder
5. Go to "Actions" menu and click "Send to Topcoder"

**Actual behavior**
1. The price menu displayed on the page opened after clicking "Send to Topcoder"  is always 0.
2. The description is showing HTML tags like br, div

**Expected behavior**
1. Price money should be what was set earlier through topcoder x tab'
2. HTML rendering is not done here. The HTML should be rendered before displaying to end user

**Environment**
- OS: Windows 10
- Device (w/version): Laptop, Windows 10
- Browser: Chrome 86.0.4240.198

![1](https://user-images.githubusercontent.com/46344490/99056875-f63be100-25c0-11eb-8241-ba13c6f083be.PNG)

**Comment by jmgasper** [comment]
Duplicates https://github.com/topcoder-platform/tcx-azure-devops-ext/issues/59
