### ISSUE TITLE
Missing field to add prizes for rank 2nd, 3rd or more in "Topcoder X" tab

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/tcx-azure-devops-ext#69]
**Steps to reproduce the problem**
1. Open Azure DevOps, create organization, and add the TCX extension from marketplace
2. Open Board -> Work items.
2. Create new epic with title, description, date and priority > Save
4. Go to "Topcoder X" tab and fill challenging details including the Prize amount

**Actual behavior**
Currently the co-pilot/admin can only add prize money for the 1st prize. There's no way to add prize money for other rank holders

**Expected behavior**
Other rank holders' prize money field should be available

**Environment**
- OS: Windows 10
- Device (w/version): Laptop, Windows 10
- Browser: Chrome 86.0.4240.198

![1](https://user-images.githubusercontent.com/46344490/99057603-086a4f00-25c2-11eb-9e26-284437cd061c.PNG)

**Comment by jmgasper** [comment]
This is alright for now.
