### ISSUE TITLE
Start and Target date don't match on Azure and Topcoder

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/tcx-azure-devops-ext#71]
**Steps to reproduce the problem**
1. Open Azure DevOps, create organization, and add the TCX extension from marketplace
2. Open Board -> Work items.
2. Create new epic with title, description, date and priority > Save
4. Go to "Topcoder X" tab and fill challenging details > Send to Topcoder
5. Open the challenge page

**Actual behavior**
The date's set on DevOps platform under planning don't match with dates shown on topcoder

**Expected behavior**
The dates should match

**Environment**
- OS: Windows 10
- Device (w/version): Laptop, Windows 10
- Browser: Chrome 86.0.4240.198

![1](https://user-images.githubusercontent.com/46344490/99058355-1d93ad80-25c3-11eb-8023-df2bf7764a9c.PNG)
![2](https://user-images.githubusercontent.com/46344490/99058360-1f5d7100-25c3-11eb-9f97-4c05b7579935.PNG)

**Comment by jmgasper** [comment]
This isn't something we sync from Azure to TC.  Those are two separate data fields on each platform
