### ISSUE TITLE
Delete or change the state (To Do, Doing, Done) from the plugin list won't take effect

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/tcx-azure-devops-ext#73]
![image](https://user-images.githubusercontent.com/42398485/99059992-5df42b00-25c5-11eb-92a7-8a9afc80c002.png)

### Steps to reproduce the problem

1. Deploy the app and create the initial setup
2. Open Board -> Work items.
3. Open or create a work item (Issue).
4. Fill the details (Description with formatting) > Save
5. Click Send to Topcoder
6. Delete the item from the plugin or change the status
7. Check the challenge

 ### Actual behavior
- Delete or change the state (To Do, Doing, Done) from the plugin list won't take effect

### Expected behavior
- Should delete if user delete an item from the plugin
 
#### Environment
**- OS:** 10
**- Device (w/version):** Laptop, Windows 10 
**- Browser** 86.0.4240.183

**Comment by jmgasper** [comment]
This is Azure functionality, not our plugin.
