### ISSUE TITLE
Table size changes with Sort

### ISSUE THREAD

**Issue by swap12875** [topcoder-platform/tcx-azure-devops-ext#80]
**Steps to reproduce the problem**

1. Deploy the app and create the initial setup
2. Go to Topcoder X Hub
3. Go to Challenges
4. try Sorting the table with different sorting options available by clicking on the sort options.

**Snaps**
[Swap12875 _Issue-1.zip](https://github.com/topcoder-platform/tcx-azure-devops-ext/files/5538892/Swap12875._Issue-1.zip)

**Actual behavior**
The size of the table is changing at each sort action

**Expected behavior**
The actual size of the displayed initially should remain unchanged.

**Environment**
- Device (w/version): Laptop, Windows 10
- Browser Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- Microsoft Edge Version 86.0.622.68 (Official build) (64-bit)

**Comment by jmgasper** [comment]
Videos are tough to follow, and also seems to duplicate https://github.com/topcoder-platform/tcx-azure-devops-ext/issues/75
